version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"  
    open-pull-requests-limit: 20
      
  # Enable version updates for nuget
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
    open-pull-requests-limit: 20
