version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
      
  # Enable version updates for nuget
  - package-ecosystem: "nuget"
    directory: "/"
    open-pull-requests-limit: 20
