version: '3.7'
services:
  cs2-server:
    build:
      context: ./resources
      dockerfile: Dockerfile
    # image: joedwards32/cs2
    env_file:
      - .env
    volumes:
      - $PWD/cs2:/home/steam/cs2-dedicated/  # (Change /mnt/cs2 according to your volume location)
    ports:
      - "27015:27015/tcp"           # TCP
      - "27015:27015/udp"           # UDP
      - "27020:27020/udp"           # UDP
      - "27022:22/tcp"              # SSH
    stdin_open: true
    tty: true