namespace PugSharp.Api.G5Api;

public enum CsWeaponId
{
    NONE = 0,
    P228,
    GLOCK,
    SCOUT,
    HEGRENADE,
    XM1014,
    C4,
    MAC10,
    AUG,
    SMOKEGRENADE,
    ELITE,
    FIVESEVEN,
    UMP45,
    SG550,
    GALIL,
    FAMAS,
    USP,
    AWP,
    MP5NAVY,
    M249,
    M3,
    M4A1,
    TMP,
    G3SG1,
    FLASHBANG,
    DEAGLE,
    SG552,
    AK47,
    KNIFE,
    P90,
    SHIELD,
    KEVLAR,
    ASSAULTSUIT,
    NIGHTVISION, //Anything below is CS:GO ONLY
    GALILAR,
    BIZON,
    MAG7,
    NEGEV,
    SAWEDOFF,
    TEC9,
    TASER,
    HKP2000,
    MP7,
    MP9,
    NOVA,
    P250,
    SCAR17,
    SCAR20,
    SG556,
    SSG08,
    KNIFE_GG,
    MOLOTOV,
    DECOY,
    INCGRENADE,
    DEFUSER,
    HEAVYASSAULTSUIT,
    //The rest are actual item definition indexes for CS:GO
    CUTTERS = 56,
    HEALTHSHOT = 57,
    KNIFE_T = 59,
    M4A1_SILENCER = 60,
    USP_SILENCER = 61,
    CZ75A = 63,
    REVOLVER = 64,
    TAGGRENADE = 68,
    FISTS = 69,
    BREACHCHARGE = 70,
    TABLET = 72,
    MELEE = 74,
    AXE = 75,
    HAMMER = 76,
    SPANNER = 78,
    KNIFE_GHOST = 80,
    FIREBOMB = 81,
    DIVERSION = 82,
    FRAGGRENADE = 83,
    SNOWBALL = 84,
    BUMPMINE = 85,
    MAX_WEAPONS_NO_KNIFES, // Max without the knife item defs, useful when treating all knives as a regular knife.
    BAYONET = 500,
    KNIFE_CLASSIC = 503,
    KNIFE_FLIP = 505,
    KNIFE_GUT = 506,
    KNIFE_KARAMBIT = 507,
    KNIFE_M9_BAYONET = 508,
    KNIFE_TATICAL = 509,
    KNIFE_FALCHION = 512,
    KNIFE_SURVIVAL_BOWIE = 514,
    KNIFE_BUTTERFLY = 515,
    KNIFE_PUSH = 516,
    KNIFE_CORD = 517,
    KNIFE_CANIS = 518,
    KNIFE_URSUS = 519,
    KNIFE_GYPSY_JACKKNIFE = 520,
    KNIFE_OUTDOOR = 521,
    KNIFE_STILETTO = 522,
    KNIFE_WIDOWMAKER = 523,
    KNIFE_SKELETON = 525,
    MAX_WEAPONS, //THIS MUST BE LAST, EASY WAY TO CREATE LOOPS. When looping, do CS_IsValidWeaponID(i), to check.
};
