namespace PugSharp.Shared;

public enum CSWeaponId
{
    None = 0,
    P228,
    Glock,
    Scout,
    HEGrenade,
    XM1014,
    C4,
    MAC10,
    AUG,
    SmokeGrenade,
    Elite,
    FiveSeven,
    UMP45,
    SG550,
    Galil,
    Famas,
    USP,
    AWP,
    MP5Navy,
    M249,
    M3,
    M4A1,
    TMP,
    G3SG1,
    Flashbang,
    Deagle,
    SG552,
    AK47,
    Knife,
    P90,
    Shield,
    Kevlar,
    Assaultsuit,
    Nightvision, //Anything below is CS:GO ONLY
    GALILAR,
    Bizon,
    MAG7,
    Negev,
    SawedOff,
    TEC9,
    Taser,
    HKP2000,
    MP7,
    MP9,
    NOVA,
    P250,
    SCAR17,
    SCAR20,
    SG556,
    SSG08,
    Knife_GG,
    Molotov,
    Decoy,
    IncGrenade,
    Defuser,
    HeavyAssaultsuit,
    //The rest are actual item definition indexes for CS:GO
    Cutters = 56,
    HealthShot = 57,
    Knife_T = 59,
    M4A1_Silencer = 60,
    USP_Silencer = 61,
    CZ75A = 63,
    Revolver = 64,
    TagGrenade = 68,
    Fists = 69,
    BreachCharge = 70,
    Tablet = 72,
    Melee = 74,
    Axe = 75,
    Hammer = 76,
    Spanner = 78,
    Knife_Ghost = 80,
    Firebomb = 81,
    Diversion = 82,
    FragGrenade = 83,
    Snowball = 84,
    Bumpmine = 85,
    Max_Weapons_No_Knifes, // Max without the knife item defs, useful when treating all knives as a regular knife.
    Bayonet = 500,
    Knife_Classic = 503,
    Knife_Flip = 505,
    Knife_Gut = 506,
    Knife_Karambit = 507,
    Knife_M9_Bayonet = 508,
    Knife_Tactical = 509,
    Knife_Falchion = 512,
    Knife_Survival_Bowie = 514,
    Knife_Butterfly = 515,
    Knife_Push = 516,
    Knife_Cord = 517,
    Knife_Canis = 518,
    Knife_Ursus = 519,
    Knife_Gypsy_JackKnife = 520,
    Knife_Outdoor = 521,
    Knife_Stiletto = 522,
    Knife_Widowmaker = 523,
    Knife_Skeleton = 525,
    Max_Weapons, //THIS MUST BE LAST, EASY WAY TO CREATE LOOPS. When looping, do CS_IsValidWeaponID(i), to check.
};
